package:
  name: aimio
  version: "1.0.0"

source:
  git_url: https://github.com/Numerics88/AimIO
  git_rev: v1.0.0

build:
  number: 0

requirements:
  build:
    - cmake
    - boost
    - n88util
  run:
    - boost
    - n88util

about:
  home: http://www.numerics88.com/
  license: MIT
  summary: Utility functions by Numerics88
